Repository bacalhau-project/bacalhau, pull requests merged in 2022-09, with the labels that each got.

#542 Integration tests refactoring
  Makefile
  pkg/computenode/job_selection_test.go
  pkg/computenode/tooling/docker.go
  pkg/computenode/tooling/noop.go
  pkg/computenode/tooling/suite.go
  pkg/devstack/devstack_ipfs.go
  pkg/storage/ipfs_apicopy/storage.go
  pkg/storage/url/urldownload/storage.go
  pkg/test/computenode/jobselection_test.go
  pkg/test/computenode/resourcelimits_test.go
  pkg/test/computenode/runjob_test.go
  pkg/test/computenode/utils.go
  pkg/test/devstack/combodriver_test.go
  pkg/test/devstack/concurrency_test.go
  pkg/test/devstack/devstack_test.go
  pkg/test/devstack/errorlogs_test.go
  pkg/test/devstack/jobselection_test.go
  pkg/test/executor/docker_executor_test.go
  pkg/test/ipfs/ipfs_host_storage_test.go
  pkg/test/ipfs/utils.go
  pkg/test/utils/stack.go
Labels: testing

#553 540 local devstack hangs on get
  cmd/bacalhau/get.go
  pkg/devstack/devstack.go
Labels: bug

#687 [updatecli] Ops Bacalhau Dependency
  ops/terraform/development.tfvars
Labels: dependencies
