Repository bacalhau-project/bacalhau, pull requests merged in 2022-10, with the labels that each got.

#789 [updatecli] Ops Bacalhau Dependency
  ops/terraform/development.tfvars
  ops/terraform/staging.tfvars
Labels: dependencies

#930 Return stdout and stderr from WASM jobs even if they fail.
  pkg/executor/wasm/executor.go
Labels: enhancement

#974 [updatecli] Ops Bacalhau Dependency
  ops/terraform/development.tfvars
  ops/terraform/production.tfvars
  ops/terraform/staging.tfvars
Labels: dependencies

#975 [updatecli] Ops Bacalhau Dependency
  ops/terraform/development.tfvars
  ops/terraform/production.tfvars
  ops/terraform/staging.tfvars
Labels: dependencies

#976 [updatecli] Ops Bacalhau Dependency
  ops/terraform/development.tfvars
  ops/terraform/production.tfvars
  ops/terraform/staging.tfvars
Labels: dependencies

#982 [updatecli] Ops Bacalhau Dependency
  ops/terraform/development.tfvars
  ops/terraform/production.tfvars
  ops/terraform/staging.tfvars
Labels: dependencies

#984 [updatecli] Ops Bacalhau Dependency
  ops/terraform/development.tfvars
  ops/terraform/production.tfvars
  ops/terraform/staging.tfvars
Labels: dependencies

#987 Fix canary to look in correct results folder
  ops/aws/canary/lambda/pkg/scenarios/submitAndGet.go
Labels: bug
