Repository bacalhau-project/bacalhau, pull requests merged in 2022-11, with the labels that each got.

#1027 Support volumes with slashes for WASM jobs
  pkg/test/scenario/test_scenarios.go
  pkg/util/mountfs/fs.go
  pkg/util/mountfs/fs_test.go
Labels: bug

#1167 [updatecli] Ops Bacalhau Dependency
  ops/aws/canary/lambda/go.mod
  ops/aws/canary/lambda/go.sum
  ops/terraform/development.tfvars
  ops/terraform/production.tfvars
  ops/terraform/staging.tfvars
Labels: dependencies

#1208 Ensure Docker is running for any test that needs it.
  pkg/test/utils/utils.go
Labels: testing

#1214 [WIP] Add Swag/OpenAPI deps
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  docs/swagger/README.md
  docs/swagger/endpoints_events.md
  docs/swagger/endpoints_list.md
  docs/swagger/endpoints_peers.md
  docs/swagger/endpoints_results.md
  docs/swagger/endpoints_states.md
  docs/swagger/endpoints_submit.md
  go.mod
  go.sum
  pkg/model/buildversion.go
  pkg/model/job.go
  pkg/model/resource_usage.go
  pkg/model/storage_spec.go
  pkg/publicapi/endpoints_debug.go
  pkg/publicapi/endpoints_events.go
  pkg/publicapi/endpoints_id.go
  pkg/publicapi/endpoints_list.go
  pkg/publicapi/endpoints_localevents.go
  pkg/publicapi/endpoints_peers.go
  pkg/publicapi/endpoints_results.go
  pkg/publicapi/endpoints_states.go
  pkg/publicapi/endpoints_submit.go
  pkg/publicapi/endpoints_version.go
  pkg/publicapi/server.go
  pkg/publicapi/server_health.go
  poetry.lock
Labels: documentation

#1279 1215 add swagger docs generation to ci
  .circleci/config.yml
  .circleci/dependency-ops.yaml
  Makefile
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  ops/repo_init.sh
  pkg/publicapi/server.go
Labels: ops

#1288 ci build swagger docs
  .circleci/config.yml
Labels: documentation

#1300 Build Swagger docs: Automatic commit from CircleCI [skip ci]
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: documentation

#1309 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: documentation

#1368 ci build swagger docs
  .circleci/config.yml
Labels: documentation

#1371 ci build swagger docs
  pkg/system/config.go
  pkg/system/tracer.go
  pkg/system/tracer_test.go
Labels: documentation

#1411 CI swagger docs: new gh PAT + PR branch name is unique (generated aut…
  .circleci/config.yml
Labels: bug, documentation

#1419 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: documentation
