Repository bacalhau-project/bacalhau, pull requests merged in 2023-04, with the labels that each got.

#2286 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/docs.go
  docs/swagger.json
Labels: schema

#2294 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/docs.go
  docs/swagger.json
Labels: schema

#2310 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/docs.go
  docs/swagger.json
Labels: schema

#2344 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/docs.go
  docs/swagger.json
Labels: schema

#2346 Ensure the minimum number of bids is reached before execution starts
  pkg/bidstrategy/callback_bid_strategy.go
  pkg/bidstrategy/fixed_strategy.go
  pkg/compute/bidder.go
  pkg/model/execution_state.go
  pkg/requester/scheduler.go
  pkg/test/compute/async_bid_test.go
  pkg/test/devstack/min_bids_test.go
  pkg/test/logstream/stream_address_test.go
  pkg/test/scenario/suite.go
Labels: bug

#2308 feat: serve default node type is requester - fixes #2305
  cmd/bacalhau/serve.go
  cmd/bacalhau/serve_test.go
Labels: feature, go

#2356 fix(ci): build and publish py sdk in two separate steps
  Makefile
  python/Makefile
Labels: python

#2374 Allows bprotocol to process errors with responses
  pkg/transport/bprotocol/compute_handler.go
  pkg/transport/bprotocol/compute_handler_test.go
  pkg/transport/bprotocol/compute_proxy.go
  pkg/transport/bprotocol/types.go
Labels: bug

#2390 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/docs.go
  docs/swagger.json
Labels: schema
