Repository bacalhau-project/bacalhau, pull requests merged in 2023-03, with the labels that each got.

#2111 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/docs.go
  docs/swagger.json
Labels: schema

#2118 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/swagger.json
Labels: schema

#2123 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/swagger.json
Labels: schema

#2172 Better handling of pypi version scheme
  .circleci/config.yml
  Makefile
  docs/swagger.json
Labels: ci/cd

#2173 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/swagger.json
Labels: schema

#2175 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/swagger.json
Labels: schema

#2206 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/docs.go
  docs/swagger.json
Labels: schema

#2209 Add log message describing where to find debug API
  cmd/bacalhau/devstack.go
  cmd/bacalhau/serve.go
  pkg/compute/publicapi/server.go
Labels: station

#2223 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/docs.go
  docs/swagger.json
Labels: schema

#2221 fix(ci): python sdk release
  python/Makefile
Labels: ci/cd

#2233 [circleci] Build swagger reference - this is an automatic commit [skip ci]
  docs/docs.go
  docs/swagger.json
Labels: schema
