Repository bacalhau-project/bacalhau, pull requests merged in 2024-03, with the labels that each got.

#3089 Implement new and improved terraform-base deployment
  ops/marketplace-tf/backend.tf
  ops/marketplace-tf/main.tf
  ops/marketplace-tf/modules/cloud-init/cloud-init.yml
  ops/marketplace-tf/modules/gcp/compute_instances/compute/main.tf
  ops/marketplace-tf/modules/gcp/compute_instances/compute/outputs.tf
  ops/marketplace-tf/modules/gcp/compute_instances/compute/variables.tf
  ops/marketplace-tf/modules/gcp/compute_instances/requester/main.tf
  ops/marketplace-tf/modules/gcp/compute_instances/requester/outputs.tf
  ops/marketplace-tf/modules/gcp/compute_instances/requester/variables.tf
  ops/marketplace-tf/modules/gcp/network/main.tf
  ops/marketplace-tf/modules/gcp/network/outputs.tf
  ops/marketplace-tf/modules/gcp/network/variables.tf
  ops/marketplace-tf/modules/instance_files/authn_policy.rego
  ops/marketplace-tf/modules/instance_files/authz_policy.rego
  ops/marketplace-tf/modules/instance_files/bacalhau.service
  ops/marketplace-tf/modules/instance_files/compute_config.yaml
  ops/marketplace-tf/modules/instance_files/install-bacalhau.sh
  ops/marketplace-tf/modules/instance_files/otel-collector.yaml
  ops/marketplace-tf/modules/instance_files/otel.service
  ops/marketplace-tf/modules/instance_files/requester_config.yaml
  ops/marketplace-tf/modules/instance_files/start.sh
  ops/marketplace-tf/outputs.tf
  ops/marketplace-tf/variables.tf
  ops/marketplace-tf/vars.tfvars
  ops/metrics/terraform/cloud-init/cloud-init.yml
  ops/metrics/terraform/gcp/backend.tf
  ops/metrics/terraform/gcp/main.tf
  ops/metrics/terraform/gcp/modules/compute_instances/otelcollector/main.tf
  ops/metrics/terraform/gcp/modules/compute_instances/otelcollector/outputs.tf
  ops/metrics/terraform/gcp/modules/compute_instances/otelcollector/variables.tf
  ops/metrics/terraform/gcp/modules/network/main.tf
  ops/metrics/terraform/gcp/modules/network/outputs.tf
  ops/metrics/terraform/gcp/modules/network/variables.tf
  ops/metrics/terraform/gcp/outputs.tf
  ops/metrics/terraform/gcp/variables.tf
  ops/metrics/terraform/gcp/vars.tfvars
  ops/metrics/terraform/instance_files/otel-collector-config.yaml
  ops/metrics/terraform/instance_files/otel.service
  ops/metrics/terraform/instance_files/start.sh
Labels: enhancement, tech-debt, feature

#3634 Fix documentation not being built or deployed.
  .github/workflows/docs.yaml
  docs/docs/dev/cli-reference/cli/job/exec/_category.yml
  docs/docs/dev/cli-reference/cli/job/exec/index.md
  docs/docs/setting-up/running-node/quick-start.md
  docs/docs/topic-guides/custom-job-types.md
Labels: bug

#3655 Default local publisher to binding to all addresses
  pkg/publisher/local/publisher.go
Labels: need-for-release

#3660 Local publisher address tf
  ops/terraform/main.tf
  ops/terraform/remote_files/scripts/start-bacalhau.sh
  pkg/publisher/local/publisher.go
  pkg/publisher/local/publisher_test.go
  pkg/publisher/local/server.go
Labels: need-for-release

#3656 Publisher processing for exec command
  cmd/cli/exec/exec.go
Labels: need-for-release

#3672 Allow nodes to call register on startup, even if previously registered
  pkg/compute/management_client.go
  pkg/node/manager/node_manager.go
Labels: need-for-release
