Repository bacalhau-project/bacalhau, pull requests merged in 2024-09, with the labels that each got.

#4482 fix: lock when accessing internal map
  pkg/lib/collections/hashed_priority_queue.go
Labels: th/game-day

#4498 introduce system.GlobalConfig + migrate installation id
  cmd/cli/root.go
  cmd/cli/serve/serve.go
  cmd/util/api.go
  pkg/analytics/analytics.go
  pkg/compute/endpoint.go
  pkg/compute/executor_buffer.go
  pkg/config/config.go
  pkg/docker/tracing/traced.go
  pkg/eventhandler/context_provider.go
  pkg/executor/wasm/executor.go
  pkg/executor/wasm/loader.go
  pkg/executor/wasm/trace.go
  pkg/nats/pubsub/pubsub.go
  pkg/node/requester.go
  pkg/orchestrator/transformer/job.go
  pkg/publisher/tracing/tracing.go
  pkg/pubsub/buffering_pubsub.go
  pkg/repo/migrations/helpers.go
  pkg/repo/migrations/v3_4.go
  pkg/repo/migrations/v3_4_test.go
  pkg/routing/tracing/tracing.go
  pkg/storage/tracing/tracing.go
  pkg/system/config.go
  pkg/telemetry/tracer.go
  pkg/telemetry/tracer_test.go
  pkg/util/targzip/targzip.go
  pkg/version/update.go
Labels: build/go

#4527 update to latest nats server
  go.mod
  go.sum
  go.work.sum
  pkg/nats/transport/nats.go
Labels: build/go

#4537 better error for db in use
  pkg/compute/store/boltdb/store.go
  pkg/jobstore/boltdb/database.go
  pkg/jobstore/boltdb/database_test.go
  pkg/jobstore/boltdb/store.go
  pkg/lib/boltdblib/db.go
  pkg/lib/boltdblib/errors.go
Labels: build/go

#4551 release steps added for python clients and sdk
  Makefile
  buildkite/pipelines/bacalhau-python.yaml
  buildkite/scripts/build_python_client.sh
  buildkite/scripts/build_python_sdk.sh
  buildkite/scripts/generate_swagger.sh
  clients/Earthfile
  clients/Makefile
  python/Earthfile
  python/Makefile
Labels: build/python
