Repository bacalhau-project/bacalhau, pull requests merged in 2024-04, with the labels that each got.

#3752 Print ranking failures in the CLI
  cmd/util/printer/print.go
  pkg/jobstore/boltdb/store.go
  test/errors.sh
  testdata/jobs/custom-task-type.yaml
Labels: bug

#3707 Generate certificates requester three
  cmd/cli/serve/serve.go
  cmd/cli/serve/serve_test.go
  cmd/cli/serve/timeout_test.go
  cmd/testing/basetls.go
  cmd/util/flags/configflags/api.go
  pkg/config/getters.go
  pkg/config/keys.go
  pkg/config/types/generated_constants.go
  pkg/config/types/generated_viper_defaults.go
  pkg/config/types/node.go
  pkg/lib/crypto/certificate.go
  pkg/lib/crypto/certificate_test.go
  pkg/lib/crypto/keys.go
  pkg/node/node.go
  pkg/publicapi/server.go
  pkg/test/utils/certificates/certificates.go
  testdata/certs/dev-ca.crt
  testdata/certs/dev-ca.key
  testdata/certs/dev-server.cnf
  testdata/certs/dev-server.crt
  testdata/certs/dev-server.csr
  testdata/certs/dev-server.key
Labels: blocked

#3769 Ensure compute node labels are published over LibP2P connections
  pkg/node/compute.go
  pkg/node/node.go
  test/labels.sh
Labels: bug

#3770 Print command line executable when displaying additional commands
  cmd/util/printer/print.go
  cmd/util/printer/print_legacy.go
Labels: bug

#3771 Structured events in place of comment strings
  cmd/cli/docker/docker_run_test.go
  cmd/cli/job/describe.go
  cmd/cli/job/executions.go
  cmd/cli/job/history.go
  cmd/util/output/output.go
  cmd/util/printer/print.go
  go.mod
  pkg/compute/bidder.go
  pkg/compute/events.go
  pkg/compute/executor.go
  pkg/compute/executor_buffer.go
  pkg/compute/types.go
  pkg/config/getters.go
  pkg/docker/docker.go
  pkg/executor/docker/bidstrategy/semantic/image_platform.go
  pkg/executor/docker/executor.go
  pkg/jobstore/boltdb/store.go
  pkg/jobstore/boltdb/store_test.go
  pkg/jobstore/mocks.go
  pkg/jobstore/types.go
  pkg/models/error.go
  pkg/models/error_test.go
  pkg/models/event.go
  pkg/models/event_test.go
  pkg/models/execution.go
  pkg/models/job_history.go
  pkg/models/plan.go
  pkg/models/plan_test.go
  pkg/orchestrator/endpoint.go
  pkg/orchestrator/errors.go
  pkg/orchestrator/events.go
  pkg/orchestrator/planner/compute_forwarder.go
  pkg/orchestrator/planner/compute_forwarder_test.go
  pkg/orchestrator/planner/event_emitter.go
  pkg/orchestrator/planner/logging_planner.go
  pkg/orchestrator/planner/state_updater.go
  pkg/orchestrator/planner/state_updater_test.go
  pkg/orchestrator/planner/utils_test.go
  pkg/orchestrator/scheduler/batch_service_job.go
  pkg/orchestrator/scheduler/constants.go
  pkg/orchestrator/scheduler/daemon_job.go
  pkg/orchestrator/scheduler/ops_job.go
  pkg/orchestrator/scheduler/types.go
  pkg/orchestrator/scheduler/types_test.go
  pkg/orchestrator/selection/ranking/features.go
  pkg/orchestrator/selection/ranking/fixed.go
  pkg/orchestrator/selection/ranking/labels.go
  pkg/orchestrator/selection/ranking/max_usage.go
  pkg/orchestrator/selection/ranking/min_version.go
  pkg/orchestrator/selection/ranking/previous_executions.go
  pkg/orchestrator/types.go
  pkg/requester/endpoint.go
  pkg/test/logstream/stream_address_test.go
  pkg/test/requester/retries_test.go
Labels: enhancement

#3795 Removing placeholders
  docs/docs/getting-started/resources.md
Labels: th/documentation
